apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    env: dev
  name: cluster-a-dev-deny-all-test
  namespace: test
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    env: pro
  name: cluster-a-pro-deny-all-test
  namespace: test
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    env: test
  name: cluster-a-test-deny-all-test
  namespace: test
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
